import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createServer} from 'node:http';import {fileURLToPath} from 'node:url';
const workspace=fileURLToPath(new URL('..',import.meta.url));
const publicRoot=path.join(workspace,'public'),output=path.join(workspace,'tmp/psychology-module-design-20261002/content/implementation');
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=';
const stamp=Date.parse('2026-10-02T09:14:00+08:00');
const libraryItem=(n)=>({id:'fixture-copy-'+n,media_type:'video',status:'done',auto_extract:true,source_url:'https://example.invalid/source/'+n,content:{title:['Signs your boundaries are getting stronger','Why some people need space after conflict'][n-1]||'A small reminder',transcript:'Synthetic original text',caption:'Demo caption'},created_at:stamp,completed_at:stamp,variantCount:5,enabledVariantCount:4,pendingVariantCount:1,rewriteModels:[{label:'Claude Sonnet 5',count:5}],peer:{accountUsername:'@demo_psych_'+n,playCount:n===1?0:null,likeCount:n===1?0:null,commentCount:2,favoriteCount:0,shareCount:null,publishedAt:stamp-86400000,topics:['boundaries'],voiceGender:'female',topComments:[{text:'Synthetic comment',likes:15}]}});
const templates=[{id:'psychology',label:'01 · 四图测试模板',hint:'上传 A/B/C/D 四张图片并填写对应文案。'},{id:'psychology-collage',label:'02 · 纸张拼贴模板',hint:'内容填写观点、故事线或解说稿。'},{id:'psychology-target-2',label:'03 · 单图互动测试模板',hint:'题目共用四个选项，每张图片只抽取一次。'}];
const topic={id:'fixture-topic',template:'psychology-target-2',title:'What did you notice first in this scene?',choices:['The moon','The doorway','The water','The shadows'].map((copy,i)=>({label:'ABCD'[i],copy})),image:{previewUrl:png},imagePool:{available:6,used:10},enabled:true,priority:85,revision:1,usageCount:12,lastUsedAt:stamp,category:'自我认知',revealComment:'Synthetic reveal comment'};
const stats={samples:1,medianViews:0,potentialRate:0,hitRate:0,completion:null,completionSamples:0};
const usageItem={id:'fixture-copy-1',title:'Signs your boundaries are getting stronger',media_type:'video',topics:['边界感'],created_at:stamp,rewrites:5,draws:12,originalDraws:4,rewriteDraws:8,lastDraw:stamp,samples:1,maxViews:0,medianViews:0,potentialRate:0,original:stats,rewrite:{...stats,samples:0,medianViews:null}};
const sidebar=`document.querySelector('.side-tabs').innerHTML='<a class="app-brand" href="/"><span>LF</span><b>Local Factory<small>心理学</small></b></a><div class="sidebar-group is-open" data-sidebar-group="psychology"><button class="sidebar-group-toggle"><span>心理学</span></button><div class="sidebar-group-items"><a href="/psychology-copy-library">文案库</a><a href="/psychology-topic-bank">模板题库</a><a href="/psychology-effects">数据概览</a><a href="/psychology-ops-report">运营报表</a><a href="/psychology-autopilot">自动运营</a></div></div><div class="sidebar-user"><b>Preview</b></div>';document.documentElement.dataset.sidebarReady='true';window.dispatchEvent(new Event('lf:sidebar-ready'));`;
test('browser: content dashboards preserve mobile controls, scopes, missing values and source permissions',async t=>{
 const executablePath=[process.env.CHROME_PATH,'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe','/usr/bin/google-chrome','/usr/bin/chromium'].filter(Boolean).find(p=>fs.existsSync(p));if(!executablePath){t.skip('Chrome unavailable');return;}
 fs.mkdirSync(output,{recursive:true});let canManage=true,empty=false;const requests=[],writes=[],errors=[],external=[],records=[];
 const server=createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost'),q=url.searchParams;const json=value=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(value));};
  if(url.pathname==='/access.js'){res.setHeader('Content-Type','text/javascript');res.end(sidebar);return;}
  if(url.pathname.startsWith('/api/')){
   requests.push(url.pathname+url.search);if(req.method!=='GET'){writes.push({path:url.pathname,method:req.method});res.writeHead(400);return json({error:'No writes are used by layout QA'});}
   if(url.pathname.endsWith('/api-key'))return json({configured:false});
   if(url.pathname.endsWith('/watch-accounts'))return json({accounts:[{username:'demo_psych',note:'Synthetic source'}]});
   if(url.pathname==='/api/psychology-copy-library'){const page=Number(q.get('page')||1);return json({items:empty?[]:page===1?[libraryItem(1),libraryItem(2),libraryItem(3),libraryItem(4)]:[libraryItem(5)],canManageSources:canManage,page,pages:empty?1:2,total:empty?0:21});}
   if(url.pathname==='/api/psychology-creative/copies')return json({items:[],page:1,pages:1,total:0});
   if(url.pathname==='/api/psychology-copy-library/usage'){
    if(q.has('text'))return json({content:{transcript:'Synthetic saved version body'}});
    if(q.has('copy'))return json({page:1,pages:1,total:1,items:[{kind:'original',variant:'original',title:usageItem.title,status:'usable',createdAt:stamp,draws:12,lastDraw:stamp,stats}]});
    return json({inventory:{originals:3,rewrites:5,usable:7,pending:1,disabled:0},usage:{used:1,unused:2,coverage:1/3,draws:12,originalDraws:4,rewriteDraws:8},effects:stats,copiesWithData:1,comparison:[{kind:'original',...stats},{kind:'rewrite',...stats,samples:0,medianViews:null}],items:empty?[]:[usageItem,{...usageItem,id:'fixture-copy-2',title:'Why some people need space after conflict',samples:0,maxViews:null,medianViews:null,potentialRate:null}],total:2,page:1,pages:1,updatedAt:stamp,window:{period:q.get('period'),from:'2026-09-26',to:'2026-10-02'}});
   }
   if(url.pathname.includes('/image-generation'))return json({items:[]});
   if(url.pathname.endsWith('/images'))return json({revision:1,total:2,hasMore:false,items:[{id:'used-image',status:'used',enabled:true,previewUrl:png,drawnAt:stamp},{id:'available-image',status:'available',enabled:true,previewUrl:png}]});
   if(url.pathname==='/api/psychology-template-topics'){const template=q.get('template')||'psychology';return json({templates,counts:Object.fromEntries(templates.map(x=>[x.id,{total:2,enabled:2,unused:1,availableImages:6}])),total:empty?0:2,items:empty?[]:[{...topic,template}, {...topic,id:'fixture-topic-2',template,title:'Which path would you choose today?',usageCount:3,imagePool:{available:0,used:2}}]});}
   return json({items:[],page:1,pages:1,total:0});
  }
  const routes={'/psychology-copy-library':'psychology-copy-library.html','/psychology-copy-usage':'psychology-copy-usage.html','/psychology-topic-bank':'psychology-topic-bank.html'};const name=routes[url.pathname]||url.pathname.slice(1),file=path.resolve(publicRoot,name);
  if(!file.startsWith(publicRoot+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}
  res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(file));
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
 const {default:puppeteer}=await import('puppeteer-core'),browser=await puppeteer.launch({executablePath,headless:true});t.after(()=>browser.close());const page=await browser.newPage(),origin='http://127.0.0.1:'+server.address().port;
 page.on('pageerror',e=>errors.push(e.message));await page.setRequestInterception(true);page.on('request',r=>{if(r.url().startsWith(origin)||r.url().startsWith('data:'))r.continue();else{external.push(r.url());r.abort();}});
 const snap=async(id,width)=>{await page.evaluate(()=>scrollTo(0,0));const qa=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,brokenImages:[...document.images].filter(i=>i.getClientRects().length&&i.complete&&!i.naturalWidth).map(i=>i.src),visibleInputs:[...document.querySelectorAll('main input,main select,main button')].filter(e=>e.getClientRects().length).length}));assert.equal(qa.scrollWidth,qa.width,id+' page overflow');assert.deepEqual(qa.brokenImages,[]);records.push({id,width,...qa});await page.screenshot({path:path.join(output,id+'-'+width+'.png'),fullPage:true});};
 for(const width of [1440,390]){
  await page.setViewport({width,height:1000});canManage=true;empty=false;
  await page.goto(origin+'/psychology-copy-library',{waitUntil:'networkidle0'});await page.waitForSelector('[data-view-original]');assert.equal(await page.$eval('#sourceManagement',n=>n.hidden),false);
  assert.match(await page.$eval('.library-metrics',n=>n.textContent),/0 播放/);assert.match(await page.$$eval('.library-metrics',ns=>ns[1].textContent),/— 播放/);
  await page.click('#selectPageBtn');assert.match(await page.$eval('#selectionCount',n=>n.textContent),/已选 4/);assert.equal(await page.$eval('#batchRewriteBtn',n=>n.disabled),false);await page.click('#clearSelectionBtn');
  await page.click('[data-view-original]');await page.waitForSelector('#copyPreviewDialog[open]');assert.match(await page.$eval('#previewText',n=>n.textContent),/Synthetic original/);await page.click('#closePreview');
  await page.click('[data-create-variant]');assert.equal(await page.$eval('#variantDialog',n=>n.open),true);await page.click('#closeVariant');
  await page.click('#sourceManagement summary');await page.click('#watchAccountsButton');await page.waitForSelector('#watchList a');await page.click('#closeWatchAccounts');await page.click('#sourceManagement summary');
  await page.click('#nextBtn');await page.waitForFunction(()=>document.querySelector('#pageInfo').textContent.includes('第 2'));assert.match(requests.at(-1),/page=2/);await page.click('#previousBtn');await page.waitForFunction(()=>document.querySelector('#pageInfo').textContent.includes('第 1'));
  const actionLayout=await page.$eval('.library-action-links',n=>({display:getComputedStyle(n).display,height:n.getBoundingClientRect().height,buttons:n.querySelectorAll('button').length}));assert.equal(actionLayout.display,'grid');assert.equal(actionLayout.buttons,5);assert.ok(actionLayout.height<100,'library actions remain compact');await snap('library',width);const keyReads=requests.filter(r=>r.includes('/api-key')).length;canManage=false;await page.reload({waitUntil:'networkidle0'});assert.equal(await page.$eval('#sourceManagement',n=>n.hidden),true);assert.equal(await page.$eval('#sourceActions',n=>n.hidden),true);assert.equal(await page.$eval('#apiPanel',n=>n.getClientRects().length),0);assert.equal(requests.filter(r=>r.includes('/api-key')).length,keyReads);assert.equal(await page.$('.peer-select'),null);await snap('library-viewer',width);
  canManage=true;await page.goto(origin+'/psychology-copy-usage',{waitUntil:'networkidle0'});await page.waitForFunction(()=>document.querySelector('#results').getAttribute('aria-busy')==='false');assert.match(await page.$eval('#effectCards',n=>n.textContent),/中位播放0/);assert.match(await page.$eval('#effectCards',n=>n.textContent),/平均完播率—/);await snap('usage',width);
  await page.click('#copies button');await page.waitForSelector('#versions button');await page.click('#versions button');await page.waitForFunction(()=>document.querySelector('#copyText').textContent.includes('Synthetic saved'));await page.click('#closeDetail');await page.select('#period','custom');assert.equal(await page.$eval('#fromLabel',n=>n.hidden),false);await page.$eval('#from',n=>n.value='2026-09-26');await page.$eval('#to',n=>n.value='2026-10-02');await page.click('#filters button');await page.waitForFunction(()=>document.querySelector('#results').getAttribute('aria-busy')==='false');assert.ok(requests.some(r=>r.includes('period=custom')&&r.includes('from=2026-09-26')&&r.includes('to=2026-10-02')));
  await page.goto(origin+'/psychology-topic-bank',{waitUntil:'networkidle0'});await page.waitForSelector('.bank-card');assert.equal(await page.$$eval('.bank-card',ns=>ns.length),3);assert.equal(await page.$$eval('.bank-template-preview img',ns=>ns.filter(i=>i.complete&&i.naturalWidth).length),3);await snap('topics',width);
  await page.goto(origin+'/psychology-topic-bank?template=psychology-target-2',{waitUntil:'networkidle0'});await page.waitForSelector('[data-images]');assert.match(await page.$eval('#topicList',n=>n.textContent),/可用 6 张 · 已抽取 10 张/);assert.match(await page.$eval('#topicList',n=>n.textContent),/12 次/);await snap('topic-detail',width);
  await page.click('#selectPage');assert.match(await page.$eval('#selectedCount',n=>n.textContent),/2 道/);await page.click('#clearSelected');await page.click('[data-edit]');assert.equal(await page.$eval('#editDialog',n=>n.open),true);assert.equal(await page.$eval('#topicTitle',n=>n.value),topic.title);await page.click('#editDialog [data-close]');
  await page.click('[data-images]');await page.waitForSelector('.pool-image');assert.equal(await page.$('[data-pool-toggle="used-image"]'),null);assert.ok(await page.$('[data-pool-toggle="available-image"]'));await page.click('#poolClose');
  empty=true;await page.goto(origin+'/psychology-copy-library',{waitUntil:'networkidle0'});await snap('library-empty',width);empty=false;
 }
 assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(output,'qa-results.json'),JSON.stringify({records,errors,external,writes,requests},null,2));
});