import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/psychology-transition-day.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../public/psychology-autopilot.html',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(overrides={}){return {date:'2026-10-01',timeZone:'America/Los_Angeles',enabled:false,canEnable:true,canRun:false,transition:null,preview:{eligible:116,review:60,normal:56,excluded:[]},formal:{revision:3},rounds:[{round:1,label:'午间',slotAt:Date.parse('2026-10-01T18:30:00Z'),generationStartAt:null,created:0,planned:116,published:0,skipped:0,states:{},status:'pending'},{round:2,label:'晚间',slotAt:Date.parse('2026-10-02T03:00:00Z'),generationStartAt:null,created:0,planned:116,published:0,skipped:0,states:{},status:'pending'}],...overrides};}
function harness(route){
 const requests=[],intervals=[],host={innerHTML:'',attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,fn){this.listeners[k]=fn;}},reload={listeners:{},addEventListener(k,fn){this.listeners[k]=fn;}},document={hidden:false,querySelector:s=>s==='#transitionDay'?host:s==='#reload'?reload:null};
 const context=vm.createContext({document,Date,fetch:async(path,init)=>{requests.push({path,...init,body:init.body?JSON.parse(init.body):null});const data=route?await route(requests.at(-1),requests.length):fixture();return data?.response||{ok:true,json:async()=>data};},setInterval(fn,ms){intervals.push({fn,ms});}});
 vm.runInContext(source,context);
 function click(action){host.listeners.click({target:{closest:()=>({dataset:{transitionAction:action}})}});}
 return {requests,host,reload,document,intervals,click};
}
test('bridge is visibly integrated before pools and module is independent of existing dashboard',()=>{assert.match(html,/id="transitionDay"[\s\S]*id="poolDashboard"/);assert.match(html,/<script type="module" src="\/psychology-transition-day.js"><\/script>/);assert.doesNotMatch(source,/psychology-autopilot\/dashboard|confirm\(/);});
test('visits, polling and refresh only read authenticated bridge status every 30 seconds',async()=>{const h=harness();await tick();assert.equal(h.requests.length,1);assert.equal(h.requests[0].method,'GET');assert.equal(h.requests[0].credentials,'same-origin');assert.equal(h.requests[0].cache,'no-store');assert.equal(h.intervals[0].ms,30000);h.intervals[0].fn();await tick();h.reload.listeners.click();await tick();assert.equal(h.requests.length,3);assert.ok(h.requests.every(r=>r.method==='GET'));h.document.hidden=true;h.intervals[0].fn();assert.equal(h.requests.length,3);});
test('native enable submits explicit date and fresh policy revision, never automatically runs',async()=>{let enabled=false;const h=harness(r=>{if(r.method==='POST')enabled=true;return fixture({enabled,canEnable:!enabled,canRun:enabled});});await tick();assert.match(h.host.innerHTML,/id="enableTransitionDay"/);h.click('enable');await tick();assert.deepEqual(h.requests.find(r=>r.method==='POST').body,{date:'2026-10-01',revision:3});assert.equal(h.requests.filter(r=>r.method==='POST').length,1);assert.doesNotMatch(h.host.innerHTML,/id="enableTransitionDay"/);assert.match(h.host.innerHTML,/id="runTransitionDay"/);h.click('run');await tick();assert.equal(h.requests.filter(r=>r.method==='POST').at(-1).path,'/api/psychology-autopilot/transition-day/run');assert.deepEqual(h.requests.filter(r=>r.method==='POST').at(-1).body,{date:'2026-10-01'});});
test('server eligibility gates prevent stale or fabricated buttons from mutating',async()=>{const h=harness(()=>fixture({canEnable:false,canRun:false}));await tick();h.click('enable');h.click('run');await tick();assert.ok(h.requests.every(r=>r.method==='GET'));assert.doesNotMatch(h.host.innerHTML,/id="enableTransitionDay"|id="runTransitionDay"/);});
test('publishing remains distinct from generation completion, escaping data and showing cross-day zones',async()=>{const h=harness(()=>fixture({enabled:true,preview:{eligible:116,review:60,normal:56,excluded:[{reason:'<img src=x onerror=alert(1)>'}]},rounds:[{round:1,label:'午间 <script>',slotAt:Date.parse('2026-10-01T18:30:00Z'),generationStartAt:Date.parse('2026-10-01T16:30:00Z'),created:116,published:0,skipped:2,states:{done:100,queued:16},status:'created',detail:'等待 <unsafe>'}]}));await tick();assert.match(h.host.innerHTML,/>116<\/strong><small>已创建任务/);assert.match(h.host.innerHTML,/>0<\/strong><small>已发布/);assert.doesNotMatch(h.host.innerHTML,/已生成|生成中/);assert.match(h.host.innerHTML,/10\/01 11:30/);assert.match(h.host.innerHTML,/10\/02 02:30/);assert.match(h.host.innerHTML,/10\/02 00:30/);assert.match(h.host.innerHTML,/午间 &lt;script&gt;/);assert.match(h.host.innerHTML,/等待 &lt;unsafe&gt;/);assert.match(h.host.innerHTML,/&lt;img src=x/);assert.match(h.host.innerHTML,/（1个账号）/);assert.doesNotMatch(h.host.innerHTML,/<script>|<img src=x|<unsafe>/);});
test('double mutation, refresh and polling during pending enable do not duplicate requests',async()=>{let release;const gate=new Promise(resolve=>release=resolve);const h=harness(async r=>{if(r.method==='POST'){await gate;return fixture({enabled:true,canRun:true});}return fixture();});await tick();h.click('enable');await tick();h.click('enable');h.click('run');h.click('refresh');h.intervals[0].fn();assert.equal(h.requests.length,2);assert.match(h.host.innerHTML,/id="enableTransitionDay"[^>]*disabled/);release();await tick();assert.equal(h.requests.filter(r=>r.method==='POST').length,1);assert.equal(h.host.attrs['aria-busy'],'false');});
test('failed refresh retains last truthful data and escaping of server mutation error',async()=>{let fail=false;const h=harness(r=>{if(r.method==='POST')return {response:{ok:false,json:async()=>({error:'<unsafe> no permission'})}};if(fail)throw Error('offline');return fixture();});await tick();h.click('enable');await tick();assert.match(h.host.innerHTML,/操作尚未确认成功：&lt;unsafe&gt; no permission/);fail=true;h.click('refresh');await tick();assert.match(h.host.innerHTML,/保留上次状态；读取失败：offline/);assert.match(h.host.innerHTML,/符合过渡条件 116 个账号/);});
