import {handleVideoLibrary} from '../factory-cloud/src/psychology-video-library.js';
import {handleVideoHitCleanup,collectVideoHitAssets,VIDEO_HIT_GRACE_MS} from '../factory-cloud/src/psychology-video-hit-cleanup.js';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {handleVideoHitVideos} from '../factory-cloud/src/psychology-video-hit-videos.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {deflateSync} from 'node:zlib';
import {fixture} from '../factory-cloud/src/psychology-cloud-test-fixture.js';
import {handleVideoHits} from '../factory-cloud/src/psychology-video-hits.js';
import {handleVideoHitAssets} from '../factory-cloud/src/psychology-video-hit-assets.js';
import {handleVideoHitProduction} from '../factory-cloud/src/psychology-video-hit-production.js';
import {publicSidebarModules} from '../factory-cloud/src/sidebar.js';
import {pageFileFor} from '../factory-cloud/src/pages.js';
import {pngCrc} from '../factory-cloud/src/topic-png.js';
import {toPublicUser} from '../factory-cloud/src/auth.js';
function framePng(remix){
 const width=320,height=568,rows=Buffer.alloc((width*3+1)*height);
 for(let y=0;y<height;y++)for(let x=0;x<width;x++){
  const circle=(x-160)**2+(y-220)**2<80**2,card=x>35&&x<285&&y>350&&y<490;
  const color=circle?[244,248,255]:card?[255,255,255]:remix?[220,125+Math.floor(y/16),70]:[55,110+Math.floor(y/12),190];
  const offset=y*(width*3+1)+1+x*3;for(let k=0;k<3;k++)rows[offset+k]=color[k];
 }
 const chunk=(name,bytes)=>{const b=Buffer.alloc(bytes.length+12);b.writeUInt32BE(bytes.length);b.write(name,4);bytes.copy(b,8);b.writeUInt32BE(pngCrc(b.subarray(4,-4)),b.length-4);return b;};
 const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(width);ihdr.writeUInt32BE(height,4);ihdr[8]=8;ihdr[9]=2;
 return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]);
}
test('real browser navigates source → ordered recreation child → comparison detail, preserving uploads/render and direct refresh',async t=>{
 const f=await fixture(t),store=new Map();
 f.sqlite.prepare('UPDATE factory_users SET sidebar_modules_json=?').run(JSON.stringify(['psychology-video-hits','psychology-publish','psychology-copy-library','factory-api']));
 const user=toPublicUser(f.sqlite.prepare("SELECT * FROM factory_users WHERE id='admin'").get());
 f.env.ARCHIVE={async put(k,b,options={}){const bytes=b instanceof ReadableStream?new Uint8Array(await new Response(b).arrayBuffer()):new Uint8Array(b);if(options.sha256)assert.equal(createHash('sha256').update(bytes).digest('hex'),options.sha256);store.set(k,bytes);return {};},async get(k){return store.has(k)?{body:store.get(k),size:store.get(k).length}:null;},async head(k){return store.has(k)?{}:null;},async delete(k){store.delete(k);}};
 const root=path.resolve(new URL('../public/',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1'));
 const out=path.resolve(root,'../tmp/video-hits-qa');fs.mkdirSync(out,{recursive:true});
 const files=[path.join(out,'original.png'),path.join(out,'remix.png')];files.forEach((file,i)=>fs.writeFileSync(file,framePng(Boolean(i))));
 const errors=[],external=[],reads=[];let previewImports=0;
 const server=http.createServer(async(req,res)=>{
  try{const address='http://127.0.0.1:'+server.address().port+req.url,url=new URL(address);let response;
   if(url.pathname==='/api/auth/me')response=Response.json({user,home:'/',sidebarModules:publicSidebarModules()});
   else if(url.pathname==='/api/official-tiktok/publish-accounts')response=Response.json({accounts:[{connectionId:'a',username:'alpha'}]});
   else if(url.pathname.startsWith('/api/psychology-video-library')){if(req.method==='POST')previewImports++;const parts=[];for await(const part of req)parts.push(part);const r=new Request(address,{method:req.method,headers:req.headers,...(parts.length?{body:Buffer.concat(parts)}:{})});response=await handleVideoLibrary(r,f.env,url,{user});}
   else if(url.pathname.startsWith('/api/psychology-video-hits')){if(req.method==='GET')reads.push(url.pathname);const parts=[];for await(const part of req)parts.push(part);const r=new Request(address,{method:req.method,headers:req.headers,...(parts.length?{body:Buffer.concat(parts)}:{})});response=await handleVideoHitCleanup(r,f.env,url,{user})||await handleVideoHitVideos(r,f.env,url,{user})||await handleVideoHitAssets(r,f.env,url,{user})||await handleVideoHitProduction(r,f.env,url,{user})||await handleVideoHits(r,f.env,url,{user});}
   else{const name=pageFileFor(url.pathname)||url.pathname.slice(1),target=path.resolve(root,name);if(!target.startsWith(root+path.sep)||!fs.existsSync(target)){res.writeHead(404).end();return;}response=new Response(fs.readFileSync(target),{headers:{'Content-Type':target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':target.endsWith('.svg')?'image/svg+xml':'text/html'}});}
   res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
  }catch(e){res.writeHead(e.statusCode||500,{'Content-Type':'application/json'}).end(JSON.stringify({error:e.message}));}
 });
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
 const {default:puppeteer}=await import('puppeteer-core'),browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});t.after(()=>browser.close());
 const p=await browser.newPage(),origin='http://127.0.0.1:'+server.address().port;p.on('pageerror',e=>errors.push(e.message));await p.setRequestInterception(true);p.on('request',r=>{if(r.url().startsWith(origin)||r.url().startsWith('data:')||r.url().startsWith('blob:'))r.continue();else{external.push(r.url());r.abort();}});
 const goto=async url=>p.goto(origin+url,{waitUntil:'networkidle0'}),navigation=async selector=>Promise.all([p.waitForNavigation({waitUntil:'networkidle0'}),p.click(selector)]);
 const fill=async(selector,value)=>{await p.$eval(selector,(node,value)=>node.value=value,value);};
 const screenshots=async name=>{for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width,name+' viewport overflow');if(name!=='detail'){const bounds=await p.$eval(name==='sources'?'[data-recreations]':'[data-detail]',n=>({left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right}));assert.ok(bounds.left>=0&&bounds.right<=width,name+' action must be visible without horizontal scrolling');}await p.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,0);});await p.screenshot({path:path.join(out,name+'-'+width+'.png'),fullPage:true});if(name==='recreations'&&width<650)await p.screenshot({path:path.join(out,name+'-'+width+'-viewport.png')});}};
 await p.setViewport({width:1440,height:1000});await goto('/psychology-video-hits');
 await p.click('#apiButton');await p.waitForFunction(()=>document.getElementById('apiInstructions').textContent.includes('psychology_videoHits_guide'));assert.match(await p.$eval('#apiInstructions',n=>n.textContent),/videoHits.publish/);await p.click('#apiDialog [data-close]');
 await p.click('#newSource');assert.equal(await p.$eval('#sourceForm [name=importSource]',n=>n.value),'manual');await p.type('#sourceForm [name=videoUrl]','https://www.tiktok.com/@source/video/123456789');await p.type('#sourceForm [name=title]','为什么你总担心别人不喜欢你');await p.type('#sourceForm [name=caption]','原视频发布文案');await p.type('#sourceForm [name=script]','你是否总在对话结束后，反复回想自己有没有说错话？');await navigation('#sourceForm button');
 assert.match(p.url(),/\/recreations\?id=vh-/);await p.waitForSelector('#recreationList:not([hidden])');assert.equal(await p.$eval('#workspace',n=>n.hidden),true);assert.equal(reads.some(path=>/\/frames\/|\/jobs$/.test(path)),false,'list must not preload detail images/jobs');
 await p.setViewport({width:320,height:1000});const empty=await p.$eval('#recreations td[colspan]',n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}));assert.ok(empty.width>200&&empty.height<160,'mobile empty state must span the list');await p.setViewport({width:1440,height:1000});await p.click('#newVersion');assert.equal(await p.$eval('#versionNumber',n=>n.options.length),20);await p.type('#versionForm [name=script]','当你反复确认别人是否喜欢你，先把注意力带回自己的感受。');await fill('#versionForm [name=caption]','二创视频发布文案');await navigation('#versionForm button');
 assert.match(p.url(),/\/detail\?id=vh-[a-f0-9]+&version=1$/);await p.waitForSelector('#workspace:not([hidden])');
 const id=new URL(p.url()).searchParams.get('id'),detailPath=new URL(p.url()).pathname+new URL(p.url()).search;
 await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$eval('#originalCaption',n=>n.textContent),'原视频发布文案');assert.equal(await p.$eval('#versionCaption',n=>n.textContent),'二创视频发布文案');assert.match(await p.$eval('#originalScript',n=>n.textContent),/反复回想/);assert.match(await p.$eval('#versionScript',n=>n.textContent),/自己的感受/);
 assert.equal(await p.$eval('a[data-sidebar-module="psychology-video-hits"]',n=>n.getAttribute('aria-current')),'page');
 for(const [i,button] of ['#addOriginal','#addRemix'].entries()){
  await p.click(button);await p.waitForSelector('#frameDialog[open]');await (await p.$('#frameForm input[type=file]')).uploadFile(files[i]);await p.type('#frameForm [name=text]',i?'把注意力带回自己的感受':'总担心说错话');await p.click('#frameForm button');await p.waitForFunction(()=>!document.querySelector('#frameDialog').open);
 }
 await p.click('#toggleVersion');await p.waitForFunction(()=>document.querySelector('#toggleVersion').textContent==='停用版本');assert.equal(await p.$eval('#renderVersion',n=>n.disabled),false);
 await p.waitForFunction(()=>document.querySelectorAll('.vh-images img').length===2&&[...document.querySelectorAll('.vh-images img')].every(i=>i.complete&&i.naturalWidth===320));
 assert.deepEqual(await p.$$eval('.vh-frame-text',nodes=>nodes.map(n=>n.textContent)),['总担心说错话','把注意力带回自己的感受']);
 const urls=await p.$$eval('.vh-images img',nodes=>nodes.map(n=>n.src));assert.notEqual(urls[0],urls[1]);
 const beforePreview=f.sqlite.prepare('SELECT COUNT(*) n FROM psychology_video_hit_requests').get().n;
 for(const width of [1440,390,320]){
  await p.setViewport({width,height:1000});
  for(const version of [0,1]){
   const selector='[data-preview-version="'+version+'"]';await p.click(selector);await p.waitForSelector('#imageDialog[open]');await p.waitForFunction(()=>!document.getElementById('imagePreview').hidden);
   assert.equal(await p.$eval('#imagePreview',img=>img.src),urls[version]);assert.match(await p.$eval('#imageDialogTitle',n=>n.textContent),version?/二创图/:/原图/);
   const bounds=await p.$eval('#imageDialog',d=>({x:d.getBoundingClientRect().x,right:d.getBoundingClientRect().right,height:d.getBoundingClientRect().height}));assert.ok(bounds.x>=0&&bounds.right<=width&&bounds.height<=1000,'image dialog fits viewport');
   const fitWidth=await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width);await p.click('#imageZoomIn');assert.ok(await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width)>fitWidth);
   await p.click('#imageZoomOut');assert.equal(await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width),fitWidth);
   await p.click('#imageActual');assert.equal(await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width),320);if(width===320)assert.ok(await p.$eval('#imageViewport',n=>n.scrollWidth>n.clientWidth),'original size scrolls inside the viewer');
   await p.keyboard.press('+');assert.equal(await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width),400);await p.keyboard.press('0');assert.equal(await p.$eval('#imagePreview',n=>n.getBoundingClientRect().width),fitWidth);
   assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width,'viewer must not overflow the document');
   if(version===1)await p.screenshot({path:path.join(out,'image-preview-'+width+'.png')});
   if(version===0){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.getElementById('imageDialog').open);assert.equal(await p.evaluate(()=>document.activeElement.dataset.previewVersion),'0');}
   else{await p.mouse.click(1,1);await p.waitForFunction(()=>!document.getElementById('imageDialog').open);}
  }
 }
 assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM psychology_video_hit_requests').get().n,beforePreview,'viewing/zooming must not write content');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM factory_jobs').get().n,0,'viewing must not generate jobs');
 await p.setViewport({width:1440,height:1000});
 for(const version of [0,1]){await p.click('#frames [data-frame="1"][data-version="'+version+'"]');await p.waitForSelector('#frameDialog[open]');assert.equal(await p.$eval('#frameForm [name=index]',n=>n.readOnly),true);assert.match(await p.$eval('#frameEditHelp',n=>n.textContent),/不会自动生成图片/);assert.match(await p.$eval('#frameEditHelp',n=>n.textContent),version?/当前二创版本/:/全部二创版本/);await p.click('#frameDialog [data-close]');}
 await p.click('#renderVersion');await p.waitForFunction(()=>document.querySelector('#jobs').textContent.includes('等待合成'));
 assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM factory_jobs WHERE type='psychology-video-remix'").get().n,1);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM psychology_publish_batches').get().n,0);assert.equal(f.requests.length,0);
 assert.equal(await p.$eval('#renderVersion',n=>n.disabled),true);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/已提交合成/);await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$eval('#renderVersion',n=>n.disabled),true);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/已提交合成/);
 await screenshots('detail');
 const renderedJob=f.sqlite.prepare("SELECT * FROM factory_jobs WHERE type='psychology-video-remix'").get(),renderedClip=path.join(out,'rendered-video.mp4');
 execFileSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=0x3372bb:s=320x568:d=2','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',renderedClip]);
 f.sqlite.prepare("UPDATE factory_jobs SET status='done',worker_id='fixture-renderer',result_json=?,percent=100 WHERE id=?").run(JSON.stringify({results:[{fileName:'rendered-video.mp4'}]}),renderedJob.id);
 await p.waitForFunction(()=>document.querySelector('#readyVideoStatus').textContent.includes('正在准备云端预览'));await p.waitForNetworkIdle();
 assert.equal(previewImports,1);assert.equal(await p.$eval('#readyVideoBadge',n=>n.textContent),'已合成视频');assert.equal(await p.$eval('#readyVideoPlayer',n=>n.hidden),true);
 const renderedAsset=f.sqlite.prepare('SELECT * FROM psychology_video_assets WHERE source_job_id=?').get(renderedJob.id);
 f.sqlite.prepare("UPDATE factory_jobs SET status='failed',error='fixture preview transfer failed' WHERE id=?").run('video-archive-'+renderedAsset.id);
 await p.waitForFunction(()=>document.querySelector('#readyVideoError').textContent.includes('fixture preview transfer failed'));
 assert.equal(previewImports,1,'failure does not repeat automatic preparation');assert.equal(await p.$eval('#prepareRenderedVideo',n=>n.textContent),'重试视频预览');
 await p.click('#prepareRenderedVideo');await p.waitForFunction(()=>document.querySelector('#readyVideoStatus').textContent.includes('正在准备云端预览'));await p.waitForNetworkIdle();assert.equal(previewImports,2);
 store.set(renderedAsset.r2_key,new Uint8Array(fs.readFileSync(renderedClip)));f.sqlite.prepare("UPDATE psychology_video_assets SET status='ready',file_size=? WHERE id=?").run(fs.statSync(renderedClip).size,renderedAsset.id);f.sqlite.prepare("UPDATE factory_jobs SET status='done' WHERE id=?").run('video-archive-'+renderedAsset.id);
 await p.waitForSelector('#readyVideoPlayer:not([hidden])');await p.$eval('#readyVideoPlayer',n=>n.scrollIntoView({block:'center'}));await p.waitForFunction(()=>document.querySelector('#readyVideoPreview').poster.startsWith('blob:'));
 assert.equal(await p.$eval('#readyVideoPlayer .video-cover-button',n=>getComputedStyle(n).padding),'0px');assert.equal(await p.$eval('#framePanel',n=>n.hidden),false);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/已合成视频/);assert.equal(await p.$eval('#readyVideoPreview',n=>n.paused),true);
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.$eval('#readyVideoPanel',n=>n.scrollIntoView({block:'start'}));await p.screenshot({path:path.join(out,'rendered-detail-'+width+'.png')});}
 await p.click('#readyVideoPlayer .video-cover-button');await p.waitForFunction(()=>document.querySelector('#readyVideoPreview').currentTime>0.1);await p.$eval('#readyVideoPreview',v=>v.pause());const playedAt=await p.$eval('#readyVideoPreview',v=>v.currentTime);await p.click('#refreshVideoPreview');await p.waitForNetworkIdle();assert.equal(await p.$eval('#readyVideoPreview',v=>v.currentTime),playedAt,'refresh preserves media playback position');
 await p.reload({waitUntil:'networkidle0'});assert.equal(previewImports,2,'ready cloud preview reuses its asset');
 const renderRevision=f.sqlite.prepare('SELECT revision FROM psychology_video_hit_versions WHERE source_id=? AND version=1').get(id).revision;
 f.sqlite.prepare('UPDATE psychology_video_hit_versions SET revision=revision+1 WHERE source_id=? AND version=1').run(id);await p.click('#refreshVideoPreview');await p.waitForFunction(()=>document.querySelector('#readyVideoBadge').textContent==='需重新合成');assert.equal(await p.$eval('#readyVideoPlayer',n=>n.hidden),true);assert.equal(await p.$eval('#readyVideoPreview',n=>n.getAttribute('src')),null);assert.equal(previewImports,2);
 f.sqlite.prepare('UPDATE psychology_video_hit_versions SET revision=?,cleaned_at=1 WHERE source_id=? AND version=1').run(renderRevision,id);await p.click('#refreshVideoPreview');await p.waitForFunction(()=>document.querySelector('#readyVideoPanel').hidden);assert.equal(await p.$eval('#readyVideoPreview',n=>n.getAttribute('src')),null);
 f.sqlite.prepare('UPDATE psychology_video_hit_versions SET cleaned_at=0 WHERE source_id=? AND version=1').run(id);await p.reload({waitUntil:'networkidle0'});assert.equal(previewImports,2);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM psychology_publish_batches').get().n,0);

 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.$eval('#editVersion',n=>n.disabled),false);await p.$eval('#editVersion',n=>n.scrollIntoView({block:'center'}));await p.click('#editVersion');await p.waitForSelector('#versionDialog[open]');assert.equal(await p.$eval('#versionNumber',n=>n.disabled),true);const bounds=await p.$eval('#versionDialog',d=>({x:d.getBoundingClientRect().x,right:d.getBoundingClientRect().right}));assert.ok(bounds.x>=0&&bounds.right<=width);await p.click('#versionDialog [data-close]');}
 const write=async(path,body)=>{const r=new Request(origin+'/api/psychology-video-hits/'+id+path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),...body})});const result=await handleVideoHits(r,f.env,new URL(r.url),{user});assert.equal(result.status,200,await result.clone().text());return result.json();};
 for(let version=20;version>=2;version--)await write('/versions/'+version,{revision:0,name:'二创版本 '+version,title:'第 '+version+' 版 · 从不同视角讲述',caption:'版本 '+version+' 发布文案',script:'版本 '+version+' 的独立配音文案。'});
 await p.setViewport({width:1440,height:1000});await navigation('#backToVersions');await p.waitForSelector('[data-version-row="20"]');
 assert.deepEqual(await p.$$eval('[data-version-row]',rows=>rows.map(r=>Number(r.dataset.versionRow))),Array.from({length:20},(_,i)=>i+1));assert.equal(await p.$eval('#newVersion',n=>n.disabled),true);assert.equal(await p.$eval('#workspace',n=>n.hidden),true);
 const listPath=new URL(p.url()).pathname+new URL(p.url()).search;await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$$eval('[data-version-row]',rows=>rows.length),20);await screenshots('recreations');
 await p.setViewport({width:1440,height:1000});await navigation('[data-detail="20"]');await p.waitForSelector('#workspace:not([hidden])');assert.equal(await p.$eval('#versionScript',n=>n.textContent),'版本 20 的独立配音文案。');assert.equal(await p.$eval('#renderVersion',n=>n.disabled),true);
 assert.equal(await p.$$eval('.vh-images img',nodes=>nodes.length),1);assert.match(await p.$eval('.vh-image-empty',n=>n.textContent),/待补充/);
 await p.goBack({waitUntil:'networkidle0'});assert.equal(new URL(p.url()).pathname+new URL(p.url()).search,listPath);await p.waitForSelector('[data-version-row="20"]');
 await navigation('#pageBreadcrumb a[href="/psychology-video-hits"]');await p.waitForSelector('[data-recreations]');await screenshots('sources');
 await p.setViewport({width:1440,height:1000});await navigation('[data-recreations]');await p.waitForSelector('[data-version-row="20"]');assert.equal(await p.$eval('#workspace',n=>n.hidden),true);await navigation('[data-detail="1"]');assert.equal(new URL(p.url()).pathname+new URL(p.url()).search,detailPath);
 const asset=f.sqlite.prepare('SELECT asset_id FROM psychology_video_hit_frames WHERE source_id=? AND version=0 AND frame_index=1').get(id).asset_id;
 await write('/frames/0',{revision:2,frames:[{index:21,assetId:asset,text:'第21帧原文'}]});await write('/frames/1',{revision:5,frames:[{index:21,assetId:asset,text:'第21帧二创'}]});await p.reload({waitUntil:'networkidle0'});
 await p.click('#frameNext');await p.waitForSelector('[data-frame-row="21"]');assert.deepEqual(await p.$$eval('[data-frame-row]',rows=>rows.map(r=>Number(r.dataset.frameRow))),[21]);assert.deepEqual(await p.$$eval('.vh-frame-text',nodes=>nodes.map(n=>n.textContent)),['第21帧原文','第21帧二创']);
 for(const invalid of ['/psychology-video-hits/detail?id='+id+'&version=21','/psychology-video-hits/detail?id='+id+'&version=1.5','/psychology-video-hits/recreations','/psychology-video-hits/detail?id=vh-'+'f'.repeat(32)+'&version=1']){
  await goto(invalid);assert.equal(await p.$eval('#workspace',n=>n.hidden),true);assert.equal(await p.$eval('#sourceSummary',n=>n.hidden),true);assert.notEqual(await p.$eval('#pageStatus',n=>n.textContent),'正在读取…');
 }

 await goto('/psychology-video-hits');await p.click('#newSource');await p.type('#sourceForm [name=videoUrl]','https://www.tiktok.com/@source/video/987654321');await p.type('#sourceForm [name=title]','直接传入成片的二创视频');await navigation('#sourceForm button');await p.click('#newVersion');await p.select('#versionInputMode','video');
 assert.equal(await p.$eval('#versionForm [name=script]',n=>n.required),false);assert.equal(await p.$eval('#videoFileLabel',n=>n.hidden),false);
 const movie=path.join(out,'ready-video.mp4');execFileSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=0x3372bb:s=320x568:d=1','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',movie]);await (await p.$('#versionVideoFile')).uploadFile(movie);await navigation('#versionForm button');await p.waitForSelector('#readyVideoPanel:not([hidden])');await p.$eval('#readyVideoPlayer',n=>n.scrollIntoView({block:'center'}));await p.waitForFunction(()=>document.querySelector('#readyVideoPreview').poster.startsWith('blob:'));await p.$eval('#readyVideoPreview',v=>v.play());await p.waitForFunction(()=>document.querySelector('#readyVideoPreview').currentTime>0.1);await p.$eval('#readyVideoPreview',v=>v.pause());
 assert.equal(await p.$eval('#framePanel',n=>n.hidden),true);assert.equal(await p.$eval('#renderVersion',n=>n.hidden),true);assert.equal(await p.$eval('#publishVersion',n=>n.disabled),false);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/成片已上传/);
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:path.join(out,'ready-video-'+width+'.png'),fullPage:true});}
 await p.setViewport({width:390,height:1000});await p.click('#publishVersion');await p.waitForSelector('#publishDialog[open]');await p.select('#publishAccount','a');await p.select('#publishAi','true');await p.screenshot({path:path.join(out,'ready-publish-390.png')});await p.click('#publishForm button');await p.waitForFunction(()=>!document.querySelector('#publishDialog').open);assert.equal(await p.$eval('#publishVersion',n=>n.disabled),true);assert.equal(await p.$eval('#editVersion',n=>n.disabled),true);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/待发布/);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM factory_jobs WHERE type='psychology-selected-video'").get().n,1);
 await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$eval('#publishVersion',n=>n.disabled),true);assert.equal(f.requests.length,0);
 const readySource=new URL(p.url()).searchParams.get('id'),readyDetail=new URL(p.url()).pathname+new URL(p.url()).search,readyJob=f.sqlite.prepare("SELECT id FROM factory_jobs WHERE type='psychology-selected-video'").get().id;
 f.sqlite.prepare("UPDATE factory_jobs SET status='done' WHERE id=?").run(readyJob);f.sqlite.prepare('INSERT INTO factory_publish_records(id,created_at,value_json) VALUES(?,?,?)').run('ui-receipt',Date.now(),JSON.stringify({autoTaskId:readyJob,status:'submitted',officialRemoteStatus:'published',shareLink:'https://www.tiktok.com/@alpha/video/888'}));
 await p.reload({waitUntil:'networkidle0'});assert.match(await p.$eval('#versionLifecycle',n=>n.textContent),/自动清理/);assert.equal(await p.$eval('#publishedLink',n=>n.getAttribute('href')),'https://www.tiktok.com/@alpha/video/888');
 await navigation('#backToVersions');assert.equal(await p.$$eval('[data-version-row]',rows=>rows.length),0);await p.click('[data-scope="published"]');assert.equal(await p.$$eval('[data-version-row]',rows=>rows.length),1);
 const publishedAt=f.sqlite.prepare('SELECT published_at FROM psychology_video_hit_versions WHERE source_id=?').get(readySource).published_at;await collectVideoHitAssets(f.env,{now:publishedAt+VIDEO_HIT_GRACE_MS+1000});
 await navigation('[data-detail="1"]');assert.equal(await p.$eval('#readyVideoPanel',n=>n.hidden),true);assert.equal(await p.$eval('#framePanel',n=>n.hidden),true);assert.match(await p.$eval('#versionScript',n=>n.textContent),/清理/);assert.match(await p.$eval('#versionStatus',n=>n.textContent),/已清理/);assert.equal(await p.$eval('#publishVersion',n=>n.disabled),true);
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:path.join(out,'cleaned-detail-'+width+'.png'),fullPage:true});}
 await p.click('#cleanupButton');await p.waitForSelector('#cleanupDialog[open]');await p.waitForFunction(()=>document.querySelector('#cleanupStatus').textContent.includes('已更新'));assert.match(await p.$eval('#cleanupSummary',n=>n.textContent),/已清理 1 个/);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),320);for(const width of [1440,390,320]){await p.setViewport({width,height:1000});const bounds=await p.$$eval('#cleanupSummary td[data-label]',nodes=>nodes.map(n=>({left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})));assert.ok(bounds.every(b=>b.left>=0&&b.right<=width),'all cleanup counters must be visible without horizontal scrolling');await p.screenshot({path:path.join(out,'cleanup-status-'+width+'.png')});}await p.click('#cleanupDialog [data-close]');
 await p.click('#archiveSource');await p.waitForSelector('#archiveDialog[open]');await p.click('#confirmArchive');await p.waitForFunction(()=>!document.querySelector('#archiveDialog').open);assert.equal(await p.$eval('#editSource',n=>n.disabled),true);assert.equal(await p.$eval('#archiveSource',n=>n.disabled),false);assert.equal(await p.$eval('#archiveSource',n=>n.textContent),'恢复二创');
 const archivedAt=f.sqlite.prepare('SELECT archived_at FROM psychology_video_hits WHERE id=?').get(readySource).archived_at;await collectVideoHitAssets(f.env,{now:archivedAt+VIDEO_HIT_GRACE_MS+1000});await p.reload({waitUntil:'networkidle0'});assert.match(await p.$eval('#sourceLifecycle',n=>n.textContent),/原选题、原文和原图仍长期保留/);
 await goto('/psychology-video-hits');assert.equal(await p.$$eval('[data-recreations]',nodes=>nodes.length),1);await p.select('#sourceScope','archived');await p.waitForFunction(()=>document.querySelector('#sources').textContent.includes('直接传入成片'));await navigation('[data-recreations]');await p.waitForSelector('#recreationList:not([hidden])');assert.equal(await p.$eval('#newVersion',n=>n.disabled),true);await p.click('[data-scope="published"]');await p.waitForSelector('[data-detail="1"]');
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);const bounds=await p.$eval('[data-detail="1"]',n=>({left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right}));assert.ok(bounds.left>=0&&bounds.right<=width);await p.screenshot({path:path.join(out,'published-records-'+width+'.png'),fullPage:true});}
 await navigation('[data-detail="1"]');assert.equal(new URL(p.url()).pathname+new URL(p.url()).search,readyDetail);assert.equal(await p.$eval('#publishedLink',n=>n.hidden),false);

 // Import through the real project-key gateway, then exercise both page filters.
 const {handleFactoryApi}=await import('../factory-cloud/src/factory-api.js'),{default:factoryWorker}=await import('../factory-cloud/src/index.js');
 const keyRequest=new Request(origin+'/api/factory-api/key',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),token=(await (await handleFactoryApi(keyRequest,f.env,new URL(keyRequest.url),{user})).json()).apiKey;
 const imported=async(action,params)=>{const response=await factoryWorker.fetch(new Request(origin+'/api/v1/factory',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({module:'psychology',action,params,requestId:crypto.randomUUID()})}),f.env,{});assert.equal(response.status,200,await response.clone().text());return response.json();};
 const addSource=async(title,modes,importSource)=>{const {id}=await imported('videoHits.create',{body:{externalId:crypto.randomUUID(),videoUrl:'https://www.tiktok.com/@source/video/123456789',title,...(importSource?{importSource}:{})}});for(const [i,inputMode] of modes.entries())await imported('videoHits.versions.write',{id,version:String(i+1),body:{revision:0,title:title+' · '+(i+1),inputMode}});return id;};
 const mixed=await addSource('API 导入 · 视频与图文',['video','frames','video','frames'],'gpt-dot'),videoOnly=await addSource('API 导入 · 只有视频',['video'],'future-agent'),framesOnly=await addSource('API 导入 · 只有图文',['frames']);
 await goto('/psychology-video-hits');await p.waitForSelector('[data-recreations="'+mixed+'"]');const labels=await p.$eval('[data-recreations="'+mixed+'"]',n=>n.closest('tr').textContent);assert.match(labels,/视频 2/);assert.match(labels,/图文 2/);
 await p.select('#sourceInputMode','video');await p.waitForFunction(()=>document.querySelector('#listStatus').textContent==='共 2 条来源 · 含视频二创');assert.deepEqual((await p.$$eval('[data-recreations]',nodes=>nodes.map(n=>n.dataset.recreations))).sort(),[mixed,videoOnly].sort());
 await p.select('#sourceInputMode','frames');await p.waitForFunction(()=>document.querySelector('#listStatus').textContent==='共 3 条来源 · 含图文二创');assert.deepEqual((await p.$$eval('[data-recreations]',nodes=>nodes.map(n=>n.dataset.recreations))).sort(),[id,mixed,framesOnly].sort());
 await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$eval('#sourceInputMode',n=>n.value),'frames');
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);const boxes=await p.$$eval('#sourceInputMode,#sources .vh-type-badges',nodes=>nodes.map(n=>({left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})));assert.ok(boxes.every(b=>b.left>=0&&b.right<=width));await p.screenshot({path:path.join(out,'type-sources-'+width+'.png'),fullPage:true});}
 await navigation('[data-recreations="'+mixed+'"]');assert.equal(await p.$eval('#recreationInputMode',n=>n.value),'frames');assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[2,4]);assert.deepEqual(await p.$$eval('#recreations .vh-type-frames',nodes=>nodes.map(n=>n.textContent)),['图文','图文']);
 await p.select('#recreationInputMode','video');assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[1,3]);await navigation('[data-detail="3"]');assert.equal(await p.$eval('#versionType',n=>n.textContent),'视频');await p.reload({waitUntil:'networkidle0'});await navigation('#backToVersions');assert.equal(await p.$eval('#recreationInputMode',n=>n.value),'video');
 f.sqlite.prepare("UPDATE psychology_video_hit_versions SET publish_state='published',cleaned_at=? WHERE source_id=? AND version=3").run(Date.now(),mixed);await p.reload({waitUntil:'networkidle0'});assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[1]);await p.click('[data-scope="published"]');assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[3]);assert.equal(await p.$eval('#recreations .vh-type-video',n=>n.textContent),'视频');
 await p.select('#recreationInputMode','frames');assert.equal(await p.$$eval('[data-version-row]',nodes=>nodes.length),0);assert.match(await p.$eval('#recreations',n=>n.textContent),/当前筛选暂无版本/);await p.click('[data-scope="all"]');assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[2,4]);await p.select('#recreationInputMode','all');assert.deepEqual(await p.$$eval('[data-version-row]',nodes=>nodes.map(n=>Number(n.dataset.versionRow))),[1,2,3,4]);
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);const boxes=await p.$$eval('#recreationInputMode,#recreations .vh-type-video,#recreations .vh-type-frames',nodes=>nodes.map(n=>({left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})));assert.ok(boxes.every(b=>b.left>=0&&b.right<=width));await p.screenshot({path:path.join(out,'type-recreations-'+width+'.png'),fullPage:true});}
 await navigation('[data-detail="2"]');assert.equal(await p.$eval('#versionType',n=>n.textContent),'图文');
 await goto('/psychology-video-hits');assert.ok((await p.$$eval('#sources .vh-import-badge',nodes=>nodes.map(n=>n.textContent))).includes('manual'));
 const filterAgent=async value=>{await fill('#sourceImportSource',value);await p.$eval('#sourceImportSource',n=>n.dispatchEvent(new Event('change',{bubbles:true})));await p.waitForFunction(value=>document.querySelector('#listStatus').textContent.endsWith(' · '+value),{},value);};
 await filterAgent('gpt-dot');assert.deepEqual(await p.$$eval('[data-recreations]',nodes=>nodes.map(n=>n.dataset.recreations)),[mixed]);await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$eval('#sourceImportSource',n=>n.value),'gpt-dot');
 await navigation('[data-recreations]');assert.match(await p.$eval('#sourceMeta',n=>n.textContent),/导入来源：gpt-dot/);await navigation('#pageBreadcrumb a');assert.equal(await p.$eval('#sourceImportSource',n=>n.value),'gpt-dot');
 await filterAgent('future-agent');assert.deepEqual(await p.$$eval('[data-recreations]',nodes=>nodes.map(n=>n.dataset.recreations)),[videoOnly]);
 await navigation('[data-recreations]');await p.click('#editSource');assert.equal(await p.$eval('#sourceForm [name=importSource]',n=>n.value),'future-agent');await fill('#sourceForm [name=importSource]','custom-agent');await p.click('#sourceForm button');await p.waitForFunction(()=>!document.querySelector('#sourceDialog').open);await p.waitForFunction(()=>document.getElementById('sourceMeta').textContent.includes('导入来源：custom-agent'));
 await goto('/psychology-video-hits');for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);assert.ok((await p.$$eval('#sources .vh-import-badge',nodes=>nodes.map(n=>n.textContent))).includes('custom-agent'));await p.screenshot({path:path.join(out,'import-source-'+width+'.png'),fullPage:true});}
 // Restore a archived topic, then release a full source slot and create version 21.
 await goto('/psychology-video-hits/recreations?id='+readySource);await p.$eval('#archiveSource',n=>n.scrollIntoView({block:'center'}));await p.click('#archiveSource');await p.waitForFunction(()=>document.querySelector('#archiveSource').textContent==='归档来源');assert.equal(await p.$eval('#newVersion',n=>n.disabled),false);await p.click('#newVersion');assert.equal(await p.$eval('#versionNumber',n=>n.value),'2');await p.click('#versionDialog [data-close]');
 f.sqlite.prepare("UPDATE psychology_video_hit_versions SET publish_item_id='completed-test',publish_state='published',published_at=? WHERE source_id=? AND version=20").run(Date.now()-25*3600000,id);await collectVideoHitAssets(f.env);
 await goto('/psychology-video-hits/recreations?id='+id);assert.equal(await p.$eval('#newVersion',n=>n.disabled),false);await p.click('#newVersion');assert.deepEqual(await p.$eval('#versionNumber',n=>[...n.options].map(o=>o.value)),['21']);await fill('#versionForm [name=script]','基于保留原选题继续创作的新文案。');await navigation('#versionForm button');assert.equal(new URL(p.url()).searchParams.get('version'),'21');assert.match(await p.$eval('#originalScript',n=>n.textContent),/你是否总在对话结束后/);await navigation('#backToVersions');assert.equal(await p.$eval('#newVersion',n=>n.disabled),true);assert.match(await p.$eval('#recreationStatus',n=>n.textContent),/在库 20 \/ 20/);
 await p.setViewport({width:1440,height:1000});await p.screenshot({path:path.join(out,'continued-versions.png')});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(f.requests.length,0);
});
