import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';import {pageFileFor} from '../factory-cloud/src/pages.js';import {publicSidebarModules} from '../factory-cloud/src/sidebar.js';
test('ready homepage previews media, filters, carries exact versions to photo/video/One creation and blocks stale selections',async t=>{
 const root=fileURLToPath(new URL('../public/',import.meta.url)),out=fileURLToPath(new URL('../tmp/video-hit-ready-qa/',import.meta.url));fs.mkdirSync(out,{recursive:true});const clip=path.join(out,'clip.mp4');execFileSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','testsrc2=size=320x568:rate=15:duration=4','-f','lavfi','-i','sine=frequency=440:duration=4','-c:v','libx264','-c:a','aac','-pix_fmt','yuv420p','-movflags','+faststart',clip]);
 const photo={ref:{sourceId:'vh-'+'a'.repeat(32),version:2,revision:4},title:'When you need a little space',caption:'A gentle reminder to set healthy boundaries. #psychology',name:'二创 2',importSource:'gpt-dot',ownerUsername:'bot1',canPhoto:true,canVideo:false,frames:[1,2,3].map(index=>({index,previewUrl:'/photo.svg?i='+index,text:'配图文案 '+index}))};
 const video={ref:{sourceId:'vh-'+'b'.repeat(32),version:1,revision:3},title:'Small signs of emotional growth',caption:'Notice the small changes. #selfgrowth',name:'二创 1',importSource:'grokbot',ownerUsername:'admin',canPhoto:false,canVideo:true,assetId:'ready-asset',previewUrl:'/clip.mp4',frames:[]};
 const rows=[photo,video],errors=[],calls=[];let stale=false,receivers=[{connectionId:'a',username:'alpha'},{connectionId:'b',username:'receiver_beta'}];
 const server=http.createServer(async(req,res)=>{try{
  const url=new URL(req.url,'http://127.0.0.1');const chunks=[];for await(const c of req)chunks.push(c);const body=chunks.length?JSON.parse(Buffer.concat(chunks).toString()):null;if(url.pathname.startsWith('/api/'))calls.push({path:url.pathname,method:req.method,body});let data;
  if(url.pathname==='/api/auth/me')data={user:{id:'admin',username:'admin',role:'admin',sidebarModules:['psychology-video-hits','psychology-publish']},sidebarModules:publicSidebarModules()};
  else if(url.pathname==='/api/psychology-video-hits/ready'){
   const id=url.searchParams.get('sourceId'),kind=url.searchParams.get('mediaType'),q=url.searchParams.get('q')||'',agent=url.searchParams.get('importSource')||'';
   if(stale&&id){res.writeHead(409,{'Content-Type':'application/json'}).end(JSON.stringify({error:'素材已提交发布，请返回待发布素材重新选择。'}));return;}
   const filtered=rows.filter(r=>(!id||r.ref.sourceId===id)&&(!q||r.title.includes(q))&&(!agent||r.importSource===agent));const items=filtered.filter(r=>kind==='photo'?r.canPhoto:kind==='video'?r.canVideo:true);data={items,total:items.length,page:1,pageSize:12,hasMore:false,canPublish:true,counts:{total:filtered.length,photos:filtered.filter(r=>r.canPhoto).length,videos:filtered.filter(r=>r.canVideo).length}};
  }else if(url.pathname==='/api/psychology-video-hits/photo-library')data={items:[{...photo,eligible:true,frameCount:3}],total:1,page:1,hasMore:false};
  else if(url.pathname==='/api/psychology-video-hits')data={items:[],total:0,page:1,pageSize:20};
  else if(url.pathname==='/api/psychology-auto-publish/photo-receivers')data={revision:1,receivers,mention:'Take your test at {account}.'};
  else if(url.pathname==='/api/psychology-auto-publish/options')data={templates:{video:[{id:'psychology',label:'四图测试'}],photo:[{id:'photo-text',label:'图文'}]},counts:{},canUseVideoHits:true,canUseTopics:true,musicPool:[]};
  else if(url.pathname==='/api/official-tiktok/publish-accounts')data={accounts:[{connectionId:'a',username:'alpha',followersCount:2000}],groups:[]};
  else if(url.pathname==='/api/psychology-auto-publish')data=req.method==='POST'?{accepted:true,batchId:'test-batch'}:{batches:[],pagination:{total:0,pageSize:10,hasMore:false}};
  else if(url.pathname==='/api/psychology-video-library')data={page:1,pageSize:20,hasMore:false,videos:[{...video,id:'video-choice',videoHit:video.ref,createdAt:Date.now(),fileName:'clip.mp4'}]};
  else if(url.pathname==='/api/psychology-tiktok-one')data={connections:[]};
  else if(url.pathname==='/photo.svg'){res.writeHead(200,{'Content-Type':'image/svg+xml'}).end('<svg xmlns="http://www.w3.org/2000/svg" width="450" height="800"><rect width="450" height="800" fill="#eee6d7"/><circle cx="225" cy="480" r="75" fill="#719896"/><text x="225" y="170" text-anchor="middle" font-size="26" font-family="Georgia" fill="#223843">It is okay to need</text><text x="225" y="214" text-anchor="middle" font-size="30" font-family="Georgia" fill="#223843">a little space.</text><text x="225" y="680" text-anchor="middle" font-size="16" fill="#637776">Psychology / '+url.searchParams.get('i')+'</text></svg>');return;}
  else if(url.pathname==='/clip.mp4'){res.writeHead(200,{'Content-Type':'video/mp4'}).end(fs.readFileSync(clip));return;}
  else if(url.pathname.startsWith('/api/'))data={};
  else{const file=path.resolve(root,pageFileFor(url.pathname)||url.pathname.slice(1));if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html'}).end(fs.readFileSync(file));return;}
  res.writeHead(200,{'Content-Type':'application/json'}).end(JSON.stringify(data));
 }catch(e){res.writeHead(500).end(JSON.stringify({error:e.message}));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));
 const {default:puppeteer}=await import('puppeteer-core'),browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});t.after(()=>browser.close());const p=await browser.newPage(),origin='http://127.0.0.1:'+server.address().port;p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.setRequestInterception(true);p.on('request',r=>r.url().startsWith(origin)||r.url().startsWith('blob:')||r.url().startsWith('data:')?r.continue():r.abort());const go=url=>p.goto(origin+url,{waitUntil:'networkidle0'}),navigate=async selector=>{try{return await Promise.all([p.waitForNavigation({waitUntil:'networkidle0'}),p.click(selector)]);}catch(e){throw new Error(e.message+' '+selector+' '+await p.$eval('#message',n=>n.textContent).catch(()=>''));}};
 await p.setViewport({width:1440,height:1000});await go('/psychology-video-hits');await p.waitForSelector('.vr-card');assert.equal(await p.$eval('#sourceList',n=>n.hidden),true);assert.equal(await p.$$eval('.vr-card',r=>r.length),2);assert.equal(await p.$eval('#readyCount-all',n=>n.textContent),'2');
 await p.click('[data-preview="0"]');await p.waitForSelector('#readyPreviewDialog[open]');assert.equal(await p.$eval('#readyPreviewPosition',n=>n.textContent),'1 / 3');await p.click('#readyImageNext');assert.equal(await p.$eval('#readyPreviewText',n=>n.textContent),'配图文案 2');await p.click('#readyClosePreview');
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:path.join(out,'ready-'+width+'.png'),fullPage:true});}
 await p.setViewport({width:1440,height:1000});await p.click('[data-ready-type="video"]');await p.waitForFunction(()=>document.querySelectorAll('.vr-card').length===1);assert.match(await p.$eval('.vr-card',n=>n.textContent),/emotional growth/);
 // A playing video must be visible, not covered by an image whose hidden flag CSS overrides.
 for(const width of [1440,390]){
  await p.setViewport({width,height:1000});await go('/psychology-video-hits');await p.waitForSelector('.vr-player');await p.$eval('.vr-player',n=>n.scrollIntoView({block:'center'}));await p.waitForSelector('.vr-player .video-cover-button:not([hidden])');
  await p.click('.vr-player .video-cover-button');await p.waitForFunction(()=>document.querySelector('.vr-player video').currentTime>0.15);
  assert.equal(await p.$eval('.vr-player .video-cover-button',n=>getComputedStyle(n).display),'none','playing gallery cover must actually disappear');
  assert.equal(await p.$eval('.vr-player video',v=>{const b=v.getBoundingClientRect();return document.elementFromPoint(b.x+b.width/2,b.y+b.height/2)===v;}),true,'the video surface must receive clicks');
  const frame=()=>p.$eval('.vr-player video',v=>{const c=document.createElement('canvas');c.width=96;c.height=160;c.getContext('2d').drawImage(v,0,0,96,160);return {time:v.currentTime,pixels:c.toDataURL()};});
  const first=await frame();await p.waitForFunction(time=>document.querySelector('.vr-player video').currentTime>time+0.4,{},first.time);assert.notEqual((await frame()).pixels,first.pixels,'decoded video frames must change during playback');
  await p.$eval('.vr-player video',v=>v.pause());assert.equal(await p.$eval('.vr-player .video-cover-button',n=>getComputedStyle(n).display),'none','pause must leave native video controls accessible');
 }
 await p.setViewport({width:1440,height:1000});await go('/psychology-video-hits');await p.waitForSelector('.vr-card');
 await p.click('[data-ready-type="all"]');await p.waitForFunction(()=>document.querySelectorAll('.vr-card').length===2);await p.type('#readyImporter','gpt-dot');await p.click('#readyFilters button');await p.waitForFunction(()=>document.querySelectorAll('.vr-card').length===1);assert.match(await p.$eval('.vr-card',n=>n.textContent),/little space/);
 const photoLink=await p.$eval('.vr-primary',n=>n.getAttribute('href'));assert.match(photoLink,/readyType=photo/);assert.equal(calls.filter(c=>c.method==='POST').length,0);
 await go(photoLink);await p.waitForFunction(()=>document.querySelector('#hitPhotoCount').textContent==='已选 1 条');assert.equal(await p.$eval('#photoSource',n=>n.value),'video-hits');assert.equal(await p.$eval('#count',n=>n.value),'1');assert.equal(await p.$('#hitPhotoSelected'),null);assert.match(await p.$eval('.hit-photo-card.is-selected',n=>n.textContent),/little space/);assert.equal(calls.filter(c=>c.method==='POST').length,0);
 await p.waitForSelector('#selectVisibleAccounts:not([disabled])');await p.click('#selectVisibleAccounts');await navigate('#submitBatch');const posted=calls.find(c=>c.path==='/api/psychology-auto-publish'&&c.method==='POST').body;assert.deepEqual(posted.photoVersions,[photo.ref]);assert.equal(posted.mentionReceiver,undefined);
 await go(photoLink);await p.waitForFunction(()=>document.querySelector('#hitPhotoCount').textContent==='已选 1 条');assert.equal(await p.$eval('#mentionReceiver',n=>n.checked),false);assert.equal(await p.$eval('#photoReceiverSettings',n=>n.hidden),false);
 await p.click('#mentionReceiver');await p.waitForFunction(()=>document.querySelector('#photoReceiverStatus').textContent.includes('@receiver_beta'));assert.match(await p.$eval('#photoReceiverCta',n=>n.textContent),/@随机承接账号/);
 for(const width of [1440,390,320]){await p.setViewport({width,height:1000});await p.$eval('#photoReceiverSettings',n=>n.scrollIntoView({block:'center'}));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);await p.screenshot({path:path.join(out,'photo-receivers-'+width+'.png'),fullPage:false});}
 await p.setViewport({width:1440,height:1000});await p.waitForSelector('#selectVisibleAccounts:not([disabled])');await p.click('#selectVisibleAccounts');await navigate('#submitBatch');assert.equal(calls.filter(c=>c.path==='/api/psychology-auto-publish'&&c.method==='POST').at(-1).body.mentionReceiver,true);
 receivers=[{connectionId:'a',username:'alpha'}];await go(photoLink);await p.waitForFunction(()=>document.querySelector('#hitPhotoCount').textContent==='已选 1 条');await p.click('#mentionReceiver');await p.waitForFunction(()=>document.querySelector('#photoReceiverStatus').textContent.includes('@alpha'));await p.waitForSelector('#selectVisibleAccounts:not([disabled])');await p.click('#selectVisibleAccounts');const beforeBlocked=calls.filter(c=>c.method==='POST').length;await p.click('#submitBatch');await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('其他可用承接账号'));assert.equal(calls.filter(c=>c.method==='POST').length,beforeBlocked);await p.click('#mentionReceiver');await navigate('#submitBatch');assert.equal(calls.filter(c=>c.path==='/api/psychology-auto-publish'&&c.method==='POST').at(-1).body.mentionReceiver,undefined);
 receivers=[{connectionId:'b',username:'receiver_beta'}];
 await go('/psychology-video-hits');await navigate('.vr-primary[href*="readyType=video"]');await p.waitForFunction(()=>!document.querySelector('#readyFixedVideo').hidden);assert.match(await p.$eval('#readyFixedVideo',n=>n.textContent),/emotional growth/);assert.equal(await p.$eval('#count',n=>n.readOnly),true);await p.waitForSelector('#selectVisibleAccounts:not([disabled])');await p.click('#selectVisibleAccounts');await navigate('#submitBatch');const videoPost=calls.filter(c=>c.path==='/api/psychology-auto-publish'&&c.method==='POST').at(-1).body;assert.deepEqual(videoPost.videoVersions,[video.ref]);assert.equal(videoPost.count,1);assert.equal(videoPost.mentionReceiver,undefined);
 await go('/psychology-video-hits');await navigate('.vr-secondary a[href*="create=one"]');await p.waitForFunction(()=>document.querySelector('#selectedVideoCount').textContent==='1');assert.match(await p.$eval('#selectedVideoList',n=>n.textContent),/emotional growth/);
 stale=true;await go(photoLink);await p.waitForFunction(()=>document.querySelector('#message').textContent.includes('已提交发布'));const posts=calls.filter(c=>c.method==='POST').length;await p.waitForSelector('#selectVisibleAccounts:not([disabled])');await p.click('#selectVisibleAccounts');await p.click('#submitBatch');assert.equal(calls.filter(c=>c.method==='POST').length,posts);
 assert.deepEqual(errors,[]);
});
