import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/psychology-copy-usage.js',import.meta.url),'utf8');
const tick=()=>new Promise(r=>setImmediate(r));
const data={inventory:{originals:3,rewrites:2,usable:4,pending:1,disabled:0},usage:{used:1,unused:2,coverage:1/3,draws:4,originalDraws:3,rewriteDraws:1},effects:{samples:1,medianViews:0,potentialRate:0,hitRate:0,completion:null,completionSamples:0},copiesWithData:1,comparison:[],items:[],total:21,page:1,pages:2,window:{period:'all'}};
function harness(){const nodes=new Map(),pending=[];class Node{constructor(tag='div'){this.tag=tag;this.value='';this.children=[];this.dataset={};this.listeners={};this.disabled=false;this.hidden=false;this.open=false;this._text='';}set textContent(v){this._text=String(v);this.children=[];}get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}append(...n){this.children.push(...n);}replaceChildren(...n){this._text='';this.children=n;}setAttribute(k,v){this[k]=v;}addEventListener(k,fn){this.listeners[k]=fn;}showModal(){this.open=true;}close(){this.open=false;this.listeners.close?.();}}
 const node=id=>{if(!nodes.has(id))nodes.set(id,new Node());return nodes.get(id);};for(const [id,value] of [['period','all'],['media','all'],['usage','all'],['sort','views']])node(id).value=value;
 const context=vm.createContext({document:{getElementById:node,createElement:tag=>new Node(tag)},URLSearchParams,AbortController,Intl,Date,setTimeout,clearTimeout,fetch:(url,options)=>new Promise((resolve,reject)=>pending.push({url,options,resolve:data=>resolve({ok:true,json:async()=>data}),reject}))});vm.runInContext(source,context);
 return {node,pending,run:code=>vm.runInContext(code,context)};
}
test('UI renders zero separately from missing and sends only content filters',async()=>{const h=harness();h.pending[0].resolve(data);await tick();assert.match(h.node('effectCards').textContent,/中位播放0/);assert.match(h.node('effectCards').textContent,/平均完播率—/);assert.match(h.node('pageInfo').textContent,/21 条/);assert.equal(h.node('next').disabled,false);assert.doesNotMatch(h.pending[0].url,/account|group|publish/);assert.match(h.pending[0].url,/sort=views/);});
test('rapid period changes abort prior read and ignore late data; failure restores pagination',async()=>{const h=harness();h.pending[0].resolve(data);await tick();h.node('period').value='today';h.node('period').listeners.change();h.node('period').value='yesterday';h.node('period').listeners.change();assert.equal(h.pending[1].options.signal.aborted,true);h.pending[2].resolve({...data,window:{period:'yesterday',from:'2026-09-25',to:'2026-09-25'}});await tick();h.pending[1].resolve({...data,window:{period:'today',from:'2026-09-26',to:'2026-09-26'}});await tick();assert.match(h.node('periodLabel').textContent,/2026-09-25/);h.node('next').listeners.click();h.pending[3].reject(Error('offline'));await tick();assert.equal(h.run('state.page'),1);assert.equal(h.node('next').disabled,false);assert.equal(h.node('prev').disabled,true);assert.match(h.node('status').textContent,/offline.*保留上次结果/);});
test('version body is lazy and closing detail prevents stale updates',async()=>{const h=harness();h.pending[0].resolve(data);await tick();h.run("openDetail({id:'copy-1',title:'<img onerror=alert(1)>'})");assert.equal(h.node('detailTitle').textContent,'<img onerror=alert(1)>');assert.equal(h.node('textPanel').hidden,true);assert.equal(h.pending.length,2);assert.match(h.pending[1].url,/copy=copy-1/);h.node('closeDetail').listeners.click();assert.equal(h.pending[1].options.signal.aborted,true);h.pending[1].resolve({items:[{title:'stale'}],total:1,pages:1,page:1});await tick();assert.doesNotMatch(h.node('versions').textContent,/stale/);});
