-- Keep execution evidence on automation items, independent of disposable jobs.
ALTER TABLE psychology_publish_items ADD COLUMN execution_status TEXT NOT NULL DEFAULT '';
ALTER TABLE psychology_publish_items ADD COLUMN execution_type TEXT NOT NULL DEFAULT '';
ALTER TABLE psychology_publish_items ADD COLUMN execution_error TEXT NOT NULL DEFAULT '';
ALTER TABLE psychology_publish_items ADD COLUMN execution_updated_at INTEGER NOT NULL DEFAULT 0;
UPDATE psychology_publish_items SET
 execution_status=COALESCE((SELECT status FROM factory_jobs WHERE id=job_id),''),
 execution_type=COALESCE((SELECT type FROM factory_jobs WHERE id=job_id),''),
 execution_error=COALESCE((SELECT error FROM factory_jobs WHERE id=job_id),''),
 execution_updated_at=COALESCE((SELECT updated_at FROM factory_jobs WHERE id=job_id),0);
CREATE INDEX IF NOT EXISTS psychology_items_job ON psychology_publish_items(job_id);
CREATE TRIGGER psychology_item_execution_update AFTER UPDATE OF status,error ON factory_jobs
WHEN OLD.status IS NOT NEW.status OR OLD.error IS NOT NEW.error BEGIN
 UPDATE psychology_publish_items SET execution_status=NEW.status,execution_type=NEW.type,execution_error=NEW.error,execution_updated_at=NEW.updated_at WHERE job_id=NEW.id;
END;
CREATE TRIGGER psychology_item_execution_delete BEFORE DELETE ON factory_jobs BEGIN
 UPDATE psychology_publish_items SET execution_status=OLD.status,execution_type=OLD.type,execution_error=OLD.error,execution_updated_at=OLD.updated_at WHERE job_id=OLD.id;
END;
CREATE TRIGGER psychology_item_execution_link AFTER UPDATE OF job_id ON psychology_publish_items BEGIN
 UPDATE psychology_publish_items SET
 execution_status=COALESCE((SELECT status FROM factory_jobs WHERE id=NEW.job_id),''),
 execution_type=COALESCE((SELECT type FROM factory_jobs WHERE id=NEW.job_id),''),
 execution_error=COALESCE((SELECT error FROM factory_jobs WHERE id=NEW.job_id),''),
 execution_updated_at=COALESCE((SELECT updated_at FROM factory_jobs WHERE id=NEW.job_id),0) WHERE id=NEW.id;
END;

-- Verified Cloudflare workflow failures from 2026-09-24 investigation. No jobs are recreated.
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006616000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-007' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006599000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-001' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006616000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-009' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006604000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-010' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006612000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-011' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006615000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-012' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006616000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-014' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006599000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-013' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006667000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-020' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006625000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-022' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006623000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-023' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: Execution timed out after 120000ms',execution_updated_at=1790006710000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-025' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006627000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-026' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006614000 WHERE id='psy-auto-2d956708b9b49da09b3a5c54860117f6-027' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: 原帖图片下载失败：HTTP 520。',execution_updated_at=1790006389000 WHERE id='psy-auto-9f8cd195bd1698dba2c6ab600826cf1a-001' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006684000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-005' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006720000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-008' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006657000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-002' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006672000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-010' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006703000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-013' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006685000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-014' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006716000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-018' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006695000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-016' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006680000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-017' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: internal error, please try again later.',execution_updated_at=1790006688000 WHERE id='psy-auto-b7415645304c7a33ff2314aa8c08c03a-019' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: 原帖图片下载失败：HTTP 403。',execution_updated_at=1789920481000 WHERE id='psy-auto-d5bd6b558f15994b35ee41dd8ed41bdb-006' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
UPDATE psychology_publish_items SET execution_status='failed',execution_type='psychology-photo-story',execution_error='Error: Pexels 搜索失败：HTTP 403',execution_updated_at=1789920544000 WHERE id='psy-auto-d5bd6b558f15994b35ee41dd8ed41bdb-015' AND deleted_at=0 AND receipt_json='{}' AND ready_json='{}' AND NOT EXISTS(SELECT 1 FROM factory_jobs WHERE id=psychology_publish_items.job_id);
