-- Canonical strategy overlays avoid rebuilding legacy pilot CHECK constraints.
ALTER TABLE psychology_autopilots ADD COLUMN current_strategy TEXT NOT NULL DEFAULT '';
ALTER TABLE psychology_autopilots ADD COLUMN strategy_started_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE psychology_autopilots ADD COLUMN pending_strategy TEXT NOT NULL DEFAULT '';
ALTER TABLE psychology_autopilots ADD COLUMN strategy_effective_at INTEGER NOT NULL DEFAULT 0;

-- Attribute each batch to its frozen strategy, including future strategy slots.
DROP TRIGGER ops_pilot_slot_insert;
CREATE TRIGGER ops_pilot_slot_insert AFTER INSERT ON psychology_autopilot_slots WHEN NEW.batch_id<>'' BEGIN INSERT OR IGNORE INTO ops_pilot_batches(batch_id,pilot_id,group_id,group_name,strategy) SELECT trim(j.value),p.id,p.group_id,p.group_name,COALESCE(CASE WHEN json_valid(b.config_json) THEN CASE WHEN json_extract(b.config_json,'$.libraryStrategy') IN ('pools','evolve','original','rewrite') THEN json_extract(b.config_json,'$.libraryStrategy') END END, CASE WHEN p.pending_strategy<>'' AND p.strategy_effective_at>0 AND NEW.slot_at>=p.strategy_effective_at THEN p.pending_strategy ELSE COALESCE(NULLIF(p.current_strategy,''),p.strategy) END) FROM psychology_autopilots p,json_each('['||replace(json_quote(NEW.batch_id),',','","')||']') j LEFT JOIN psychology_publish_batches b ON b.id=trim(j.value) WHERE p.id=NEW.autopilot_id AND trim(j.value)<>''; INSERT INTO ops_task_dirty(item_id) SELECT id FROM psychology_publish_items WHERE batch_id IN (SELECT trim(value) FROM json_each('['||replace(json_quote(NEW.batch_id),',','","')||']')) ON CONFLICT(item_id) DO UPDATE SET revision=lower(hex(randomblob(16))); END;

DROP TRIGGER ops_pilot_slot_update;
CREATE TRIGGER ops_pilot_slot_update AFTER UPDATE OF batch_id ON psychology_autopilot_slots WHEN NEW.batch_id<>'' BEGIN INSERT OR IGNORE INTO ops_pilot_batches(batch_id,pilot_id,group_id,group_name,strategy) SELECT trim(j.value),p.id,p.group_id,p.group_name,COALESCE(CASE WHEN json_valid(b.config_json) THEN CASE WHEN json_extract(b.config_json,'$.libraryStrategy') IN ('pools','evolve','original','rewrite') THEN json_extract(b.config_json,'$.libraryStrategy') END END, CASE WHEN p.pending_strategy<>'' AND p.strategy_effective_at>0 AND NEW.slot_at>=p.strategy_effective_at THEN p.pending_strategy ELSE COALESCE(NULLIF(p.current_strategy,''),p.strategy) END) FROM psychology_autopilots p,json_each('['||replace(json_quote(NEW.batch_id),',','","')||']') j LEFT JOIN psychology_publish_batches b ON b.id=trim(j.value) WHERE p.id=NEW.autopilot_id AND trim(j.value)<>''; INSERT INTO ops_task_dirty(item_id) SELECT id FROM psychology_publish_items WHERE batch_id IN (SELECT trim(value) FROM json_each('['||replace(json_quote(NEW.batch_id),',','","')||']')) ON CONFLICT(item_id) DO UPDATE SET revision=lower(hex(randomblob(16))); END;
