-- Reporting-only immutable receiver identities. No media/caption copies or foreign-key cascade.
CREATE TABLE ops_photo_receivers (
 item_id TEXT PRIMARY KEY,publisher_key TEXT NOT NULL,receiver_key TEXT NOT NULL,
 receiver_username TEXT NOT NULL DEFAULT '',cta TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL
);
CREATE INDEX ops_photo_receivers_receiver ON ops_photo_receivers(receiver_key,publisher_key,created_at);
INSERT OR IGNORE INTO ops_photo_receivers(item_id,publisher_key,receiver_key,receiver_username,cta,created_at) SELECT json_extract(j.payload_json,'$.psychologyAutomation.id'),'tiktok:'||replace(json_extract(j.payload_json,'$.psychologyAutomation.connectionId'),'tiktok:',''),'tiktok:'||replace(json_extract(COALESCE(json_extract(j.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(j.payload_json,'$.importedPhotoConversion'),json_extract(j.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'),'tiktok:',''),COALESCE(json_extract(COALESCE(json_extract(j.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(j.payload_json,'$.importedPhotoConversion'),json_extract(j.payload_json,'$.psychologyAutomation.conversion')),'$.username'),''),COALESCE(json_extract(COALESCE(json_extract(j.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(j.payload_json,'$.importedPhotoConversion'),json_extract(j.payload_json,'$.psychologyAutomation.conversion')),'$.cta'),''),j.created_at
 FROM factory_jobs j
 WHERE json_extract(j.payload_json,'$.psychologyAutomation.mediaType')='photo' AND length(json_extract(j.payload_json,'$.psychologyAutomation.id'))>0 AND length(json_extract(j.payload_json,'$.psychologyAutomation.connectionId'))>0 AND length(json_extract(COALESCE(json_extract(j.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(j.payload_json,'$.importedPhotoConversion'),json_extract(j.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'))>0;
-- Older conversion jobs may already have been pruned; their frozen allocation survives.
INSERT OR IGNORE INTO ops_photo_receivers(item_id,publisher_key,receiver_key,receiver_username,cta,created_at)
 SELECT item_id,'tiktok:'||replace(connection_id,'tiktok:',''),'tiktok:'||replace(receiver_connection_id,'tiktok:',''),COALESCE(json_extract(route_json,'$.username'),''),COALESCE(json_extract(route_json,'$.cta'),''),created_at
 FROM psychology_conversion_allocations WHERE connection_id<>'' AND receiver_connection_id<>'';
CREATE TRIGGER ops_photo_receiver_job_insert AFTER INSERT ON factory_jobs BEGIN
 INSERT OR IGNORE INTO ops_photo_receivers(item_id,publisher_key,receiver_key,receiver_username,cta,created_at) SELECT json_extract(NEW.payload_json,'$.psychologyAutomation.id'),'tiktok:'||replace(json_extract(NEW.payload_json,'$.psychologyAutomation.connectionId'),'tiktok:',''),'tiktok:'||replace(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'),'tiktok:',''),COALESCE(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.username'),''),COALESCE(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.cta'),''),NEW.created_at

 WHERE json_extract(NEW.payload_json,'$.psychologyAutomation.mediaType')='photo' AND length(json_extract(NEW.payload_json,'$.psychologyAutomation.id'))>0 AND length(json_extract(NEW.payload_json,'$.psychologyAutomation.connectionId'))>0 AND length(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'))>0;
END;
CREATE TRIGGER ops_photo_receiver_job_update AFTER UPDATE OF payload_json ON factory_jobs BEGIN
 INSERT OR IGNORE INTO ops_photo_receivers(item_id,publisher_key,receiver_key,receiver_username,cta,created_at) SELECT json_extract(NEW.payload_json,'$.psychologyAutomation.id'),'tiktok:'||replace(json_extract(NEW.payload_json,'$.psychologyAutomation.connectionId'),'tiktok:',''),'tiktok:'||replace(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'),'tiktok:',''),COALESCE(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.username'),''),COALESCE(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.cta'),''),NEW.created_at

 WHERE json_extract(NEW.payload_json,'$.psychologyAutomation.mediaType')='photo' AND length(json_extract(NEW.payload_json,'$.psychologyAutomation.id'))>0 AND length(json_extract(NEW.payload_json,'$.psychologyAutomation.connectionId'))>0 AND length(json_extract(COALESCE(json_extract(NEW.payload_json,'$.psychologyAutomation.photoReceiver'),json_extract(NEW.payload_json,'$.importedPhotoConversion'),json_extract(NEW.payload_json,'$.psychologyAutomation.conversion')),'$.receiverConnectionId'))>0;
END;
